// Generated by gencpp from file pckg/move_pos_group.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_MOVE_POS_GROUP_H
#define PCKG_MESSAGE_MOVE_POS_GROUP_H

#include <ros/service_traits.h>


#include <pckg/move_pos_groupRequest.h>
#include <pckg/move_pos_groupResponse.h>


namespace pckg
{

struct move_pos_group
{

typedef move_pos_groupRequest Request;
typedef move_pos_groupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_pos_group
} // namespace pckg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pckg::move_pos_group > {
  static const char* value()
  {
    return "fcf1b3f28988025a9decb7235f491f13";
  }

  static const char* value(const ::pckg::move_pos_group&) { return value(); }
};

template<>
struct DataType< ::pckg::move_pos_group > {
  static const char* value()
  {
    return "pckg/move_pos_group";
  }

  static const char* value(const ::pckg::move_pos_group&) { return value(); }
};


// service_traits::MD5Sum< ::pckg::move_pos_groupRequest> should match
// service_traits::MD5Sum< ::pckg::move_pos_group >
template<>
struct MD5Sum< ::pckg::move_pos_groupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_group >::value();
  }
  static const char* value(const ::pckg::move_pos_groupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_groupRequest> should match
// service_traits::DataType< ::pckg::move_pos_group >
template<>
struct DataType< ::pckg::move_pos_groupRequest>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_group >::value();
  }
  static const char* value(const ::pckg::move_pos_groupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pckg::move_pos_groupResponse> should match
// service_traits::MD5Sum< ::pckg::move_pos_group >
template<>
struct MD5Sum< ::pckg::move_pos_groupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_group >::value();
  }
  static const char* value(const ::pckg::move_pos_groupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_groupResponse> should match
// service_traits::DataType< ::pckg::move_pos_group >
template<>
struct DataType< ::pckg::move_pos_groupResponse>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_group >::value();
  }
  static const char* value(const ::pckg::move_pos_groupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCKG_MESSAGE_MOVE_POS_GROUP_H
