// Generated by gencpp from file pckg/move_pos_simu.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_MOVE_POS_SIMU_H
#define PCKG_MESSAGE_MOVE_POS_SIMU_H

#include <ros/service_traits.h>


#include <pckg/move_pos_simuRequest.h>
#include <pckg/move_pos_simuResponse.h>


namespace pckg
{

struct move_pos_simu
{

typedef move_pos_simuRequest Request;
typedef move_pos_simuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_pos_simu
} // namespace pckg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pckg::move_pos_simu > {
  static const char* value()
  {
    return "fcf1b3f28988025a9decb7235f491f13";
  }

  static const char* value(const ::pckg::move_pos_simu&) { return value(); }
};

template<>
struct DataType< ::pckg::move_pos_simu > {
  static const char* value()
  {
    return "pckg/move_pos_simu";
  }

  static const char* value(const ::pckg::move_pos_simu&) { return value(); }
};


// service_traits::MD5Sum< ::pckg::move_pos_simuRequest> should match
// service_traits::MD5Sum< ::pckg::move_pos_simu >
template<>
struct MD5Sum< ::pckg::move_pos_simuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_simu >::value();
  }
  static const char* value(const ::pckg::move_pos_simuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_simuRequest> should match
// service_traits::DataType< ::pckg::move_pos_simu >
template<>
struct DataType< ::pckg::move_pos_simuRequest>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_simu >::value();
  }
  static const char* value(const ::pckg::move_pos_simuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pckg::move_pos_simuResponse> should match
// service_traits::MD5Sum< ::pckg::move_pos_simu >
template<>
struct MD5Sum< ::pckg::move_pos_simuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_simu >::value();
  }
  static const char* value(const ::pckg::move_pos_simuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_simuResponse> should match
// service_traits::DataType< ::pckg::move_pos_simu >
template<>
struct DataType< ::pckg::move_pos_simuResponse>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_simu >::value();
  }
  static const char* value(const ::pckg::move_pos_simuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCKG_MESSAGE_MOVE_POS_SIMU_H
