// Generated by gencpp from file pckg/move_pos_traj.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_MOVE_POS_TRAJ_H
#define PCKG_MESSAGE_MOVE_POS_TRAJ_H

#include <ros/service_traits.h>


#include <pckg/move_pos_trajRequest.h>
#include <pckg/move_pos_trajResponse.h>


namespace pckg
{

struct move_pos_traj
{

typedef move_pos_trajRequest Request;
typedef move_pos_trajResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_pos_traj
} // namespace pckg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pckg::move_pos_traj > {
  static const char* value()
  {
    return "49e8e74c01da16a8f0f7f7669e48bf05";
  }

  static const char* value(const ::pckg::move_pos_traj&) { return value(); }
};

template<>
struct DataType< ::pckg::move_pos_traj > {
  static const char* value()
  {
    return "pckg/move_pos_traj";
  }

  static const char* value(const ::pckg::move_pos_traj&) { return value(); }
};


// service_traits::MD5Sum< ::pckg::move_pos_trajRequest> should match
// service_traits::MD5Sum< ::pckg::move_pos_traj >
template<>
struct MD5Sum< ::pckg::move_pos_trajRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_traj >::value();
  }
  static const char* value(const ::pckg::move_pos_trajRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_trajRequest> should match
// service_traits::DataType< ::pckg::move_pos_traj >
template<>
struct DataType< ::pckg::move_pos_trajRequest>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_traj >::value();
  }
  static const char* value(const ::pckg::move_pos_trajRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pckg::move_pos_trajResponse> should match
// service_traits::MD5Sum< ::pckg::move_pos_traj >
template<>
struct MD5Sum< ::pckg::move_pos_trajResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_traj >::value();
  }
  static const char* value(const ::pckg::move_pos_trajResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_trajResponse> should match
// service_traits::DataType< ::pckg::move_pos_traj >
template<>
struct DataType< ::pckg::move_pos_trajResponse>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_traj >::value();
  }
  static const char* value(const ::pckg::move_pos_trajResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCKG_MESSAGE_MOVE_POS_TRAJ_H
