// Generated by gencpp from file pckg/move_pos_single.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_MOVE_POS_SINGLE_H
#define PCKG_MESSAGE_MOVE_POS_SINGLE_H

#include <ros/service_traits.h>


#include <pckg/move_pos_singleRequest.h>
#include <pckg/move_pos_singleResponse.h>


namespace pckg
{

struct move_pos_single
{

typedef move_pos_singleRequest Request;
typedef move_pos_singleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_pos_single
} // namespace pckg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pckg::move_pos_single > {
  static const char* value()
  {
    return "0c0bf682ee407d9ffa1c8714b3dcfa29";
  }

  static const char* value(const ::pckg::move_pos_single&) { return value(); }
};

template<>
struct DataType< ::pckg::move_pos_single > {
  static const char* value()
  {
    return "pckg/move_pos_single";
  }

  static const char* value(const ::pckg::move_pos_single&) { return value(); }
};


// service_traits::MD5Sum< ::pckg::move_pos_singleRequest> should match
// service_traits::MD5Sum< ::pckg::move_pos_single >
template<>
struct MD5Sum< ::pckg::move_pos_singleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_single >::value();
  }
  static const char* value(const ::pckg::move_pos_singleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_singleRequest> should match
// service_traits::DataType< ::pckg::move_pos_single >
template<>
struct DataType< ::pckg::move_pos_singleRequest>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_single >::value();
  }
  static const char* value(const ::pckg::move_pos_singleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pckg::move_pos_singleResponse> should match
// service_traits::MD5Sum< ::pckg::move_pos_single >
template<>
struct MD5Sum< ::pckg::move_pos_singleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::move_pos_single >::value();
  }
  static const char* value(const ::pckg::move_pos_singleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::move_pos_singleResponse> should match
// service_traits::DataType< ::pckg::move_pos_single >
template<>
struct DataType< ::pckg::move_pos_singleResponse>
{
  static const char* value()
  {
    return DataType< ::pckg::move_pos_single >::value();
  }
  static const char* value(const ::pckg::move_pos_singleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCKG_MESSAGE_MOVE_POS_SINGLE_H
