// Generated by gencpp from file pckg/move_pos_trajRequest.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_MOVE_POS_TRAJREQUEST_H
#define PCKG_MESSAGE_MOVE_POS_TRAJREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pckg
{
template <class ContainerAllocator>
struct move_pos_trajRequest_
{
  typedef move_pos_trajRequest_<ContainerAllocator> Type;

  move_pos_trajRequest_()
    : pos()
    , vel(0.0)  {
    }
  move_pos_trajRequest_(const ContainerAllocator& _alloc)
    : pos(_alloc)
    , vel(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pos_type;
  _pos_type pos;

   typedef double _vel_type;
  _vel_type vel;





  typedef boost::shared_ptr< ::pckg::move_pos_trajRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pckg::move_pos_trajRequest_<ContainerAllocator> const> ConstPtr;

}; // struct move_pos_trajRequest_

typedef ::pckg::move_pos_trajRequest_<std::allocator<void> > move_pos_trajRequest;

typedef boost::shared_ptr< ::pckg::move_pos_trajRequest > move_pos_trajRequestPtr;
typedef boost::shared_ptr< ::pckg::move_pos_trajRequest const> move_pos_trajRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pckg::move_pos_trajRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pckg::move_pos_trajRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pckg::move_pos_trajRequest_<ContainerAllocator1> & lhs, const ::pckg::move_pos_trajRequest_<ContainerAllocator2> & rhs)
{
  return lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pckg::move_pos_trajRequest_<ContainerAllocator1> & lhs, const ::pckg::move_pos_trajRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pckg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pckg::move_pos_trajRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pckg::move_pos_trajRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pckg::move_pos_trajRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32cfa15d7a180f82c21a2042da6bcd82";
  }

  static const char* value(const ::pckg::move_pos_trajRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32cfa15d7a180f82ULL;
  static const uint64_t static_value2 = 0xc21a2042da6bcd82ULL;
};

template<class ContainerAllocator>
struct DataType< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pckg/move_pos_trajRequest";
  }

  static const char* value(const ::pckg::move_pos_trajRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] pos\n"
"float64 vel\n"
;
  }

  static const char* value(const ::pckg::move_pos_trajRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos);
      stream.next(m.vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_pos_trajRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pckg::move_pos_trajRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pckg::move_pos_trajRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "vel: ";
    Printer<double>::stream(s, indent + "  ", v.vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCKG_MESSAGE_MOVE_POS_TRAJREQUEST_H
