// Generated by gencpp from file pckg/track_frame.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_TRACK_FRAME_H
#define PCKG_MESSAGE_TRACK_FRAME_H

#include <ros/service_traits.h>


#include <pckg/track_frameRequest.h>
#include <pckg/track_frameResponse.h>


namespace pckg
{

struct track_frame
{

typedef track_frameRequest Request;
typedef track_frameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct track_frame
} // namespace pckg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pckg::track_frame > {
  static const char* value()
  {
    return "94287391629a6739a22a5918862fa5b1";
  }

  static const char* value(const ::pckg::track_frame&) { return value(); }
};

template<>
struct DataType< ::pckg::track_frame > {
  static const char* value()
  {
    return "pckg/track_frame";
  }

  static const char* value(const ::pckg::track_frame&) { return value(); }
};


// service_traits::MD5Sum< ::pckg::track_frameRequest> should match
// service_traits::MD5Sum< ::pckg::track_frame >
template<>
struct MD5Sum< ::pckg::track_frameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::track_frame >::value();
  }
  static const char* value(const ::pckg::track_frameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::track_frameRequest> should match
// service_traits::DataType< ::pckg::track_frame >
template<>
struct DataType< ::pckg::track_frameRequest>
{
  static const char* value()
  {
    return DataType< ::pckg::track_frame >::value();
  }
  static const char* value(const ::pckg::track_frameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pckg::track_frameResponse> should match
// service_traits::MD5Sum< ::pckg::track_frame >
template<>
struct MD5Sum< ::pckg::track_frameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pckg::track_frame >::value();
  }
  static const char* value(const ::pckg::track_frameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pckg::track_frameResponse> should match
// service_traits::DataType< ::pckg::track_frame >
template<>
struct DataType< ::pckg::track_frameResponse>
{
  static const char* value()
  {
    return DataType< ::pckg::track_frame >::value();
  }
  static const char* value(const ::pckg::track_frameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCKG_MESSAGE_TRACK_FRAME_H
