// Generated by gencpp from file pckg/track_frameRequest.msg
// DO NOT EDIT!


#ifndef PCKG_MESSAGE_TRACK_FRAMEREQUEST_H
#define PCKG_MESSAGE_TRACK_FRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pckg
{
template <class ContainerAllocator>
struct track_frameRequest_
{
  typedef track_frameRequest_<ContainerAllocator> Type;

  track_frameRequest_()
    : frame()  {
    }
  track_frameRequest_(const ContainerAllocator& _alloc)
    : frame(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_type;
  _frame_type frame;





  typedef boost::shared_ptr< ::pckg::track_frameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pckg::track_frameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct track_frameRequest_

typedef ::pckg::track_frameRequest_<std::allocator<void> > track_frameRequest;

typedef boost::shared_ptr< ::pckg::track_frameRequest > track_frameRequestPtr;
typedef boost::shared_ptr< ::pckg::track_frameRequest const> track_frameRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pckg::track_frameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pckg::track_frameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pckg::track_frameRequest_<ContainerAllocator1> & lhs, const ::pckg::track_frameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frame == rhs.frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pckg::track_frameRequest_<ContainerAllocator1> & lhs, const ::pckg::track_frameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pckg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::pckg::track_frameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pckg::track_frameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pckg::track_frameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pckg::track_frameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pckg::track_frameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pckg::track_frameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pckg::track_frameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a054304ca480f0e0c67ec5f261591b09";
  }

  static const char* value(const ::pckg::track_frameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa054304ca480f0e0ULL;
  static const uint64_t static_value2 = 0xc67ec5f261591b09ULL;
};

template<class ContainerAllocator>
struct DataType< ::pckg::track_frameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pckg/track_frameRequest";
  }

  static const char* value(const ::pckg::track_frameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pckg::track_frameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string frame\n"
;
  }

  static const char* value(const ::pckg::track_frameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pckg::track_frameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct track_frameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pckg::track_frameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pckg::track_frameRequest_<ContainerAllocator>& v)
  {
    s << indent << "frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCKG_MESSAGE_TRACK_FRAMEREQUEST_H
